### ISSUE TITLE
Historical data  output  for 5s (all timeframeinsec ) is coming in min 

### ISSUE THREAD

**Issue by quant321** [marketcalls/openalgo#115]
not able to fetch 5s /15s historical data from openalgo.
instead of giving error its providing min data respectively for sec interval ,plscheck
close    high     low  ...  volume   returns   change%
timestamp                                          ...
2024-12-13 09:15:00+05:30  242.70  244.15  241.35  ...  578460       NaN       NaN
2024-12-13 09:20:00+05:30  241.95  243.20  241.70  ...  252825 -0.003090 -0.309023
2024-12-13 09:25:00+05:30  241.85  242.50  240.90  ...  317064 -0.000413 -0.041331
2024-12-13 09:30:00+05:30  240.55  242.10  240.50  ...  194717 -0.005375 -0.537523
df = client.history(
    symbol="BHEL",
    exchange="NSE",
    interval="5s",
    start_date="2024-12-13",
    end_date="2024-12-13"
)
  ==========================
5s and 5 m both are mapped to 5
class FyersData:
    def init(self, auth_token):
        """Initialize Fyers data handler with authentication token"""
        self.auth_token = auth_token
        # Map common timeframe format to Fyers resolutions
        self.timeframe_map = {
            # Seconds
            '5s': '5', '10s': '10', '15s': '15', '30s': '30', '45s': '45',
            # Minutes
            '1m': '1', '2m': '2', '3m': '3', '5m': '5',
            '10m': '10', '15m': '15', '20m': '20', '30m': '30',

**Comment by marketcalls** [comment]
Add the Fix in the Branch Chartink-Screener Branch
Validated from my side and it is working fine.

https://github.com/marketcalls/openalgo/tree/chartink-scanner

After Chartink Strategy Module Testing will be pushing to Main Branch Shortly.

**Comment by marketcalls** [comment]
Moved to main branch upgrade to the newer version v1.0.0.17
please follow the upgrade procedure.
https://docs.openalgo.in/getting-started/upgrade

**Comment by marketcalls** [comment]
Let me know if the issue got a fix after the newer update?

**Comment by marketcalls** [comment]
Im closing this issue as the issue got sorted out. It is highly recommended to use the latest openalgo python library >=1.0.5.

Im closing this issue. Feel free to reopen if in case facing any more issue.
