### ISSUE TITLE
FivePaisa Login Issue 

### ISSUE THREAD

**Issue by crypt0inf0** [marketcalls/openalgo#117]
Unable to login on fivepaisa, I get the following error `Broker is fivepaisa
ERROR:utils.auth_utils:Authentication error: BROKER_API_KEY format is incorrect. Expected format: 'api_key:::user_id:::client_id'`

5paisa takes these credientials for login,
```
cred = {
    "APP_NAME": APP_NAME,
    "APP_SOURCE": APP_SOURCE,
    "USER_ID": USER_ID,
    "PASSWORD": PASSWORD,
    "USER_KEY": USER_KEY,
    "ENCRYPTION_KEY": ENCRYPTION_KEY
}
```

```
# Login
client = FivePaisaClient(cred=cred)

# New TOTP based authentication
client.get_totp_session(client_code,totp,mpin)
```

Ref. https://github.com/OpenApi-5p/5paisa-js/blob/main/index.js#L86
https://github.com/OpenApi-5p/py5paisa/blob/master/py5paisa/const.py#L15

**Comment by marketcalls** [comment]
In my case I tried with the documentation of OpenAlgo
https://docs.openalgo.in/connect-brokers/5paisa

Configured

```
BROKER_API_KEY = 'User_Key:::User_ID:::client_id'
BROKER_API_SECRET = 'Encryption_Key'
REDIRECT_URL = 'http://127.0.0.1:5000/fivepaisa/callback'
```

And it worked with a regular openalgo login followed by Broker Login with TOTP Credentials.

will be using client_id, pin and totp for main broker login.

**Comment by crypt0inf0** [comment]
```
BROKER_API_KEY = 'vcT1zs8yxxxxxxxxxxxxxx:::JHJAxxxxxxx:::50xxxxxx'
BROKER_API_SECRET = 'wGhfKi0lIO2uxxxxxxxxxxxxxxx'
```
