### ISSUE TITLE
 load_dotenv(dotenv_path=env_path) in env_check.py

### ISSUE THREAD

**Issue by tarakbluru** [marketcalls/openalgo#125]
please make this load_dotenv(dotenv_path=env_path, override=True) else previous set values are getting used in windows10

**Comment by marketcalls** [comment]
Sure will update in the next immedite release

**Comment by marketcalls** [comment]
Beginning with v1.0.0.17, the issue has been resolved by implementing a centralized loading of .env files through env_check, which not only fixes the original problem but also properly handles overrides.
