### ISSUE TITLE
Wrong P&L On Kambala Based Brokers

### ISSUE THREAD

**Issue by crypt0inf0** [marketcalls/openalgo#136]
Shoonya, FlatTrade & other brokers using kambala, Displays the `Realized P&L`  in negative if positive and positive if negative.

Changing https://github.com/marketcalls/openalgo/blob/main/broker/shoonya/api/funds.py#L56 to `total_realised = -float(margin_data.get('rpnl',0))` fix the issue.

**Comment by marketcalls** [comment]
ssues a fix. please do 
```git pull```
 and check it out.
