### ISSUE TITLE
Trading Positions Not Displaying LTP & P&L On FlatTrade

### ISSUE THREAD

**Issue by crypt0inf0** [marketcalls/openalgo#138]
On positions dashboard it is not displaying the LTP & P&L,
![image](https://github.com/user-attachments/assets/bb5ffe42-45f3-4c9a-9530-97b94f4bb946)

**Comment by marketcalls** [comment]
LTP and PNL will happen only after Data API implementation as currency API doesnt faciliate that..

It is a placeholder I kept for future implementation.

**Comment by crypt0inf0** [comment]
Closing this issue as data api is not implemented yet.
