### ISSUE TITLE
Flattrade order execution Issue and API Request Analyzer

### ISSUE THREAD

**Issue by tradewithmadhan** [marketcalls/openalgo#145]
Flattrade order execution Issue.

1.Sell orders are placing as buy orders .
2. API Request Analyzer not working i can able to see only one recode but i have triggered many orders ... 

Regards,
Madan

**Comment by marketcalls** [comment]
How you are firing orders. Im testing with the following end point

http://127.0.0.1:5000/api/v1/placeorder


here is the sample message works perfectly

{
    "apikey": "openalgo-api-key",
    "strategy": "my Strategy",
    "exchange": "NSE",
    "symbol": "BHEL",
    "action": "SELL",
    "product": "MIS",
    "pricetype": "MARKET",
    "quantity": "1",
    "price": "0",
    "trigger_price": "0",
    "disclosed_quantity": "0"
}
<img width="1195" alt="Screenshot 2024-12-26 at 1 00 34 PM" src="https://github.com/user-attachments/assets/5b171f68-3554-4087-8503-b2cabefba89f" />

If in case you are using placesmartorders. Then try to understand how to use it.
I will also try to make a short video explaining how placesmartorder works

For time being you can checkout the details here https://docs.openalgo.in/api-documentation/v1/orders-api/placesmartorder

**Comment by tradewithmadhan** [comment]
Suggestion : we can avoid a delay between positions check and 1st order , after that before 2nd order we can have the delay ...... in such case use can avoid the delay of 1st order / less then the freeze qty ...  Please check the feasibility .
