### ISSUE TITLE
Data Downloader using websocket

### ISSUE THREAD

**Issue by Newbie2Pro** [marketcalls/openalgo#15]
This may sound like a different project altogether.. But how about we use the broker API websocket to download data to AmiBroker, NinjaTrader, MT4, MT5, etc. Is that an enhancement that can be added to the scope of this project?

**Comment by marketcalls** [comment]
This is indeed a different project altogether and not included in the current scope of our project. The application we built is a Flask application designed to be functional across various operating systems.

However, it's important to note that:

AmiBroker runs only on Windows.
MT4 and MT5 are not designed to feed custom data, and although workarounds are possible, they may not be effective solutions.

Thus, integrating broker API websockets to download data to platforms like AmiBroker, NinjaTrader, MT4, and MT5 would require a separate development effort and isn't feasible within the current project's scope.

**Comment by marketcalls** [comment]
Right now OpenAlgo Supports Amibroker (Amiquotes) method.

OpenAlgo - Amibroker (Amiquote) Module
Now Fetch Live Realtime Data (Intraday/EOD) data into Amibroker from your Broker API automatically.
https://docs.openalgo.in/trading-platform/amibroker/amiquotes
