### ISSUE TITLE
master_contract_db.py in fyers has references to zerodha.. Please check

### ISSUE THREAD

**Issue by tarakbluru** [marketcalls/openalgo#16]
eg., https://github.com/marketcalls/openalgo/blob/e20d4d01d333261ea5fdb7e43af05aab2f775bc6/broker/fyers/database/master_contract_db.py#L85

def process_zerodha_csv(path):

I just had a quick glance. This may be by design.  May be you want to review.

**Comment by marketcalls** [comment]
Fyers implementation is in progress. Still not released yet. Current active brokers are Angel, Upstox, Zerodha

**Comment by marketcalls** [comment]
The screens for OpenAlgo on Fyers have been completed. The building and testing of the API are scheduled for Monday.
It is highly probable that the Fyers plugin for OpenAlgo will be ready by Monday.

**Comment by marketcalls** [comment]
Fyers Plugin is implemented. Will be testing in live markets this week and will be updating the patch if any.
Kindly Fork/Clone/Pull the repository fresh.
