### ISSUE TITLE
Broker Support 

### ISSUE THREAD

**Issue by Hiddenleaf07** [marketcalls/openalgo#27]
How to connect Shoonya

**Comment by marketcalls** [comment]
Shoonya is in our pipeline. But not included in the current Phase of Roadmap

This is the one in our immediate task list
https://openalgo.notion.site/31d68186651748598256e8c6dd145e0b?v=d082684ac1fe4948a39ecdb6b2a8f0a8

In the next phase we are planning to include shoonya (finvasia)

**Comment by marketcalls** [comment]
Shoonya is now integrated from v1.0.0.14 onwards.
Kindly try it out!

**Comment by marketcalls** [comment]
For Installation Procedure kindly visit OpenAlgo Documentation
https://docs.openalgo.in/getting-started
