### ISSUE TITLE
future signal to option trade

### ISSUE THREAD

**Issue by karthik-valliappan** [marketcalls/openalgo#39]
Hi, 

is there any way to convert future signal to take trade in options from trading view/Amibroker ?

Thanks,

**Comment by marketcalls** [comment]
For Amibroker you can use the module 

Single Leg Futures to Options
https://docs.openalgo.in/trading-platform/amibroker/spot-futures-to-options-module-single-leg

Two Leg Futures to Options
https://docs.openalgo.in/trading-platform/amibroker/spot-futures-to-options-module-two-leg

Tradingview tutorials are still in pipeline. yet to post
