### ISSUE TITLE
angel login error

### ISSUE THREAD

**Issue by yadu12342q** [marketcalls/openalgo#48]
![angel](https://github.com/marketcalls/openalgo/assets/167697889/54822c20-a458-40fe-8103-2008b87a461f)
every detail is fine but still getting error in login

**Comment by marketcalls** [comment]
Hi,

Ensure that you configured the .env file for angel in the below format
BROKER_API_KEY = 'your_api_key_here'
BROKER_API_SECRET = 'your_api_secret_here'
REDIRECT_URL = 'http://127.0.0.1:5000/angel/callback'

for complete config instructions you can refer
https://docs.openalgo.in/connect-brokers/angelone

Here is the sample config 

BROKER_API_KEY = 'BcM2Y9c7'
BROKER_API_SECRET = '4cRx5mDdz89rg4R'

REDIRECT_URL = 'http://127.0.0.1:5000/angel/callback'  

Also please check the VS Code Log for why the authentication is failing.

**Comment by marketcalls** [comment]
Hope your Angel Login Issue got fixed It is due to extra space while configuring the API Credentials.
