### ISSUE TITLE
Kotak Broker - Error while openig Tabs 

### ISSUE THREAD

**Issue by hemangshah36** [marketcalls/openalgo#54]
Hello,
I am getting 500 Internal Server Error while opening following tabs after logged in.

Orderbook, Tradebook, Positions (In short only Holdings & Tradingview Tabs are working)

**Error while opening Orderbook**

  order_data = mapping_funcs['map_order_data'](order_data=order_data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\openalgo\broker\kotak\mapping\order_data.py", line 19, in map_order_data
    if order_data['stat'] == 'Not_Ok':
       ~~~~~~~~~~^^^^^^^^
KeyError: 'stat'
127.0.0.1 - - [20/Jul/2024 03:30:02] "GET /orderbook HTTP/1.1" 500 -


**Error while opening Tradebook**

  File "C:\openalgo\blueprints\orders.py", line 99, in tradebook
    tradebook_data = map_trade_data(trade_data=tradebook_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\openalgo\broker\kotak\mapping\order_data.py", line 151, in map_trade_data
    if trade_data['stat'] == 'Not_Ok':
       ~~~~~~~~~~^^^^^^^^
KeyError: 'stat'
127.0.0.1 - - [20/Jul/2024 03:30:32] "GET /tradebook HTTP/1.1" 500 -


**Error while opening Positions**

   return map_order_data(position_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\openalgo\broker\kotak\mapping\order_data.py", line 19, in map_order_data
    if order_data['stat'] == 'Not_Ok':
       ~~~~~~~~~~^^^^^^^^
KeyError: 'stat'
127.0.0.1 - - [20/Jul/2024 03:32:50] "GET /positions HTTP/1.1" 500 -

![image](https://github.com/user-attachments/assets/b07c99dd-85f8-47f2-84c2-a88a74ee7f8b)

**Comment by marketcalls** [comment]
May I know why this issue got closed?

**Comment by hemangshah36** [comment]
> May I know why this issue got closed?

@marketcalls 

I did - git pull

and then randomly checked and all tabs were opening. So I believed that it's resolved in latest release and hence closed issue.

However, while checking today, exactly same issue as mentioned in original post is occurring. Hence, at this stage my belief is that issue is random. Sometimes, those tabs are opening and sometimes, get internal server error. Kindly refer first post of this thread to get detailed error logs etc.

Opened this thread in anticipation of more clarity and 100% successful working.

**Comment by hemangshah36** [comment]
It seems that it is working fine during market hours.

If we try to open those tabs outside market hours, it is giving Internal Server Error.

@marketcalls 
Kindly verify above point at your end and close the thread if you believe that my observation is correct.
