### ISSUE TITLE
Dhan broker holdings page error

### ISSUE THREAD

**Issue by tradewithmadhan** [marketcalls/openalgo#55]
only Holding page has a issue maybe since i don't have any holding ... instead of showing zero holding its gives error...

![image](https://github.com/user-attachments/assets/10d6d3aa-0ee5-455e-a112-d087ce9ac8d3)

![image](https://github.com/user-attachments/assets/8f15d3c4-840d-438d-a3df-b5e282af5f56)

**Comment by marketcalls** [comment]
Can you go to the VS Code and post the complete error log where the empty portfolio data is captured?
That will be helpful to narrow down the issue

**Comment by tradewithmadhan** [comment]
PS C:\Users\Administrator\Documents\openalgo> python app.py
Initializing Auth DB
Initializing User DB
Initializing Master Contract DB
Initializing API Log DB
 * ngrok URL: https://*********-caring-quietly.ngrok-free.app *
 * Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [20/Jul/2024 21:39:19] "GET /socket.io/?EIO=4&transport=polling&t=P3Gvw64 HTTP/1.1" 200 -
127.0.0.1 - - [20/Jul/2024 21:39:19] "POST /socket.io/?EIO=4&transport=polling&t=P3Gvw6T&sid=d8D1QkUgVo6Oy3ycAAAA HTTP/1.1" 200 -
127.0.0.1 - - [20/Jul/2024 21:39:19] "GET /socket.io/?EIO=4&transport=polling&t=P3Gvw6W&sid=d8D1QkUgVo6Oy3ycAAAA HTTP/1.1" 200 -
127.0.0.1 - - [20/Jul/2024 21:39:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Jul/2024 21:39:26] "GET /static/favicon/logo.png HTTP/1.1" 304 -
127.0.0.1 - - [20/Jul/2024 21:39:26] "GET /static/images/brokers/5paisa.png HTTP/1.1" 304 -
127.0.0.1 - - [20/Jul/2024 21:39:26] "GET /static/images/brokers/angel.png HTTP/1.1" 304 -
127.0.0.1 - - [20/Jul/2024 21:39:26] "GET /static/images/brokers/dhan.png HTTP/1.1" 304 -
127.0.0.1 - - [20/Jul/2024 21:39:26] "GET /static/images/brokers/aliceblue.png HTTP/1.1" 304 -
127.0.0.1 - - [20/Jul/2024 21:39:27] "GET /static/images/brokers/icici.png HTTP/1.1" 304 -
127.0.0.1 - - [20/Jul/2024 21:39:27] "GET /static/images/brokers/kotak.png HTTP/1.1" 304 -
127.0.0.1 - - [20/Jul/2024 21:39:27] "GET /static/images/brokers/fyers.png HTTP/1.1" 304 -
127.0.0.1 - - [20/Jul/2024 21:39:27] "GET /static/images/brokers/upstox.png HTTP/1.1" 304 -
127.0.0.1 - - [20/Jul/2024 21:39:27] "GET /static/images/thumbs-up.png HTTP/1.1" 304 -
127.0.0.1 - - [20/Jul/2024 21:39:27] "GET /static/images/brokers/zerodha.png HTTP/1.1" 304 -
127.0.0.1 - - [20/Jul/2024 21:39:27] "GET /socket.io/?EIO=4&transport=websocket&sid=d8D1QkUgVo6Oy3ycAAAA HTTP/1.1" 200 -
127.0.0.1 - - [20/Jul/2024 21:39:27] "GET /static/favicon/site.webmanifest HTTP/1.1" 304 -
127.0.0.1 - - [20/Jul/2024 21:39:29] "GET /auth/login HTTP/1.1" 302 -
127.0.0.1 - - [20/Jul/2024 21:39:29] "GET /auth/broker HTTP/1.1" 302 -
Positionbook : []
127.0.0.1 - - [20/Jul/2024 21:39:29] "GET /dashboard HTTP/1.1" 200 -
127.0.0.1 - - [20/Jul/2024 21:39:29] "GET /static/js/socket-events.js HTTP/1.1" 304 -
127.0.0.1 - - [20/Jul/2024 21:39:30] "GET /static/js/mobile-menu.js HTTP/1.1" 304 -
127.0.0.1 - - [20/Jul/2024 21:39:30] "GET /static/css/main.css HTTP/1.1" 304 -
127.0.0.1 - - [20/Jul/2024 21:39:30] "GET /static/images/thumbs-up.png HTTP/1.1" 304 -
127.0.0.1 - - [20/Jul/2024 21:39:30] "GET /static/sounds/alert.mp3 HTTP/1.1" 206 -
127.0.0.1 - - [20/Jul/2024 21:39:30] "GET /socket.io/?EIO=4&transport=polling&t=P3Gvyjc HTTP/1.1" 200 -
127.0.0.1 - - [20/Jul/2024 21:39:30] "POST /socket.io/?EIO=4&transport=polling&t=P3Gvykt&sid=K6qP9k6QqSCZUBjYAAAC HTTP/1.1" 200 -
127.0.0.1 - - [20/Jul/2024 21:39:30] "GET /socket.io/?EIO=4&transport=polling&t=P3Gvykx&sid=K6qP9k6QqSCZUBjYAAAC HTTP/1.1" 200 -
127.0.0.1 - - [20/Jul/2024 21:39:34] "GET /socket.io/?EIO=4&transport=websocket&sid=K6qP9k6QqSCZUBjYAAAC HTTP/1.1" 200 -
{'errorCode': 'HOLDING_ERROR', 'httpStatus': 'BAD_REQUEST', 'internalErrorCode': 'DH-1111', 'internalErrorMessage': 'No holdings available'}
[2024-07-20 21:39:34,466] ERROR in app: Exception on /holdings [GET]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\openalgo\blueprints\orders.py", line 185, in holdings
    holdings_data = map_portfolio_data(holdings_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\openalgo\broker\dhan\mapping\order_data.py", line 205, in map_portfolio_data
    if portfolio_data is None or (portfolio_data[0].get('internalErrorMessage') == "No holdings available"):
                                  ~~~~~~~~~~~~~~^^^
KeyError: 0
127.0.0.1 - - [20/Jul/2024 21:39:34] "GET /holdings HTTP/1.1" 500 -

**Comment by marketcalls** [comment]
This is the one Iam looking for

{'errorCode': 'HOLDING_ERROR', 'httpStatus': 'BAD_REQUEST', 'internalErrorCode': 'DH-1111', 'internalErrorMessage': 'No holdings available'}

Let me check and update the openalgo with a fix shortly.

**Comment by marketcalls** [comment]
We’ve issued a fix for the Dhan empty portfolio issue. Please update to the latest version by running the following command in your terminal:

`git pull`

Once updated, kindly check if this resolves the empty portfolio problem.

Looking forward to your confirmation.

**Comment by tradewithmadhan** [comment]
empty portfolio problem fixed.. thanks

**Comment by marketcalls** [comment]
Thanks for the confirmation
