### ISSUE TITLE
Request : Please add a dark theme feature in the next release, if possible

### ISSUE THREAD

**Issue by tradewithmadhan** [marketcalls/openalgo#58]
Please add a dark theme feature in the next release, if possible

**Comment by marketcalls** [comment]
Now OpenAlgo Supports Both Dark and Light theme in the newer version.
Kindly update to the latest OpenAlgo Version 1.0.0.12

[![Learn more about the newer UI with theme switching](https://img.youtube.com/vi/X46ysXcYz8M/0.jpg)](https://www.youtube.com/watch?v=X46ysXcYz8M)
