### ISSUE TITLE
Session error in fyers

### ISSUE THREAD

**Issue by vijaylondhe21** [marketcalls/openalgo#60]
I am using fyers for login. When I login into fyers window then it should redirect to dashboard but instead keyerror 'user' is popping up on my screen/terminal. After debugging I found that inside session storage user is saved but later when accessed in other files user is not present in session.
![IMG-20240813-WA0022](https://github.com/user-attachments/assets/02fee9cf-9b40-451b-acf6-9203e8fe8cae)

**Comment by marketcalls** [comment]
I tried from my account and the login is successful. Can you try with new apikey and secret ensure proper permission is provided to the api

**Comment by vijaylondhe21** [comment]
Just now issue is resolved in my account too. I was opening the site with localhost and redirect url was 127.0.0.1. This happened due to default port forwarding behaviour of VS code.
