### ISSUE TITLE
Login error attached

### ISSUE THREAD

**Issue by tradingideas2000** [marketcalls/openalgo#67]
after clicking login button error attached
![open](https://github.com/user-attachments/assets/b7338776-3d6b-4299-91b8-9195c26979dc)

**Comment by tradingideas2000** [comment]
noticed 17th Oct 2024 10:40 PM approx

**Comment by marketcalls** [comment]
I’ve resolved the issue, and it’s now working on openalgo.in. I hosted my own account there, but it’s separate from the open-source codebase. Traders can set up their own OpenAlgo instances on their desktop, cloud, or VPS

**Comment by tradingideas2000** [comment]
noted thanks
