### ISSUE TITLE
DB file is missing in the repo

### ISSUE THREAD

**Issue by Paragkk** [marketcalls/openalgo#69]
openalgo.db file is not present in the repo.
Where can i get the empty db file please

**Comment by marketcalls** [comment]
Hi DB will be created when you start the application in your machine for the first time. 
It is not a good idea and practice to share the DB in the repo

**Comment by Paragkk** [comment]
Thanks a lot for your response. It seems the db is not getting created due to some permission issue. I will have to dig further.

**Comment by marketcalls** [comment]
Let me know which OS you are trying to Integrate openalgo. Only for Linux it demands permissions.

**Comment by Paragkk** [comment]
I am trying on windows 10 itself. Attaching the error log.
[error.txt](https://github.com/user-attachments/files/17570480/error.txt)

**Comment by marketcalls** [comment]
Running the Python script using the full path versus running it from the directory can cause issues, especially with relative paths and imports. Here's why:

1. When you run `python3 "c:\Users\parag\PyCodes\AWS codes\openalgo\app.py"` from a different directory:
- Python sets the working directory (`os.getcwd()`) to the directory you're running the command from
- This can cause issues with relative paths in your code
- Module imports might fail if they rely on the Python path being set relative to the project root

2. When you run `python3 app.py` from the project directory:
- The working directory is correctly set to your project root
- Relative imports work as expected
- File paths resolve correctly relative to the project root

Here's how to fix this:

1. Change to the project directory first, then run the app:
```bash
cd "c:\Users\parag\PyCodes\AWS codes\openalgo"
python3 app.py
```

**Comment by Paragkk** [comment]
Thanks a lot. its working now. 👯‍♂️

**Comment by marketcalls** [comment]
I'm glad you are able to fix the issue!
