### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by Papuni1984** [marketcalls/openalgo#77]
At the starting of the day,it difficult to login .gives 500 eror

**Comment by marketcalls** [comment]
Added Robust Session Expiry Handling

**Summary of Session Expiry Implementation:**

Main Route ('/')
Main Route ('/download')

Implemented: @invalidate_session_if_invalid decorator
Why: To clear invalid sessions without redirecting, allowing both logged-in and logged-out users to access the home page and download page while maintaining session security.

**Protected Routes**

Implemented: @check_session_validity decorator
Applied to:
Dashboard ('/dashboard')
Orders ('/orderbook', '/tradebook', '/positions', '/holdings')
Search ('/search/token', '/search/', '/search/api/search')
TradingView ('/tradingview/')
Logs ('/logs/')
API Key management ('/apikey')
Password change ('/auth/change')
Why: To ensure that only authenticated users with valid sessions can access these sensitive areas of the application. It redirects to login if the session is invalid.

**Authentication Routes**

The session expiry mechanism is primarily implemented using two decorators:

**@invalidate_session_if_invalid:** Clears invalid sessions without redirecting.

**@check_session_validity:** Checks session validity and redirects to login if invalid.
These decorators work in conjunction with the session management logic in utils/session.py, which handles the actual session expiry time calculations and validations based on the configured SESSION_EXPIRY_TIME (default 3 AM IST).

**Environment Configuration:**
Added SESSION_EXPIRY_TIME to .env and .sample.env files
Set default value to '03:00' (3 AM IST)

**The session auto-logout now works in the following scenarios:**
When a user is actively using the application at 3 a.m. IST
When the browser is closed before 3 a.m. and reopened after 3 a.m.
When making any authenticated request after the session expiry time

**To verify the changes:**
The session expiry time is logged when a user logs in
Any attempt to access protected routes after 3 a.m. IST will redirect to the login page
The session expiry is enforced even if the browser was closed and reopened
The session expiry time can be modified by changing the SESSION_EXPIRY_TIME value in the .env file, making it flexible for future adjustments if needed.


This implementation ensures that most sensitive routes are protected against expired sessions, while allowing flexibility for public routes and authentication processes. The main route (/) uses a special handler to clear invalid sessions without disrupting the user experience for both logged-in and logged-out users.

**Comment by marketcalls** [comment]
Hope the issue got resolved. If not kindly reopen the ticket.
