### ISSUE TITLE
Kotak Neo Login Runtime Error

### ISSUE THREAD

**Issue by techsproutss** [marketcalls/openalgo#82]
I have added BROKER_API_KEY and BROKER_API_SECRET: for Kotak Neo. I have also created the account and logged succesfully on openalgo platform. I have confirmed that my Kotak Neo mobile number and password are working. I have used Kotak Neo Trading Terminal password to log into the broker account.

After logging into openalgo i am presented with the broker login window. After entering the mobile number is expected format and inputting the correct trading terminal password I am getting a runtime error. Have also attached the screenshot.

Have cross checked all the information at my side and everything seems to be ok at my end. I am able to log into kotak neo trading platform using the same password which is getting the run time error.

<img width="1470" alt="Screenshot 2024-11-12 at 7 08 17 PM" src="https://github.com/user-attachments/assets/55a360c3-3a4d-4b15-a484-df2d0f62a6b8">

below is the error message from the terminal

{'code': '900901', 'type': 'Status report', 'message': 'Runtime Error', 'description': 'Sandbox key offered to the API with no sandbox endpoint'}

https://github.com/user-attachments/assets/6e1a9e70-f833-4204-9ebb-3c6d04204e2f

**Comment by marketcalls** [comment]
Can you try generating the kotak api as explained in this procedure?

[![YouTube Video](https://img.youtube.com/vi/uw2PQOEBiV8/0.jpg)](https://www.youtube.com/watch?v=uw2PQOEBiV8)

**Comment by marketcalls** [comment]
does the login procedure worked?

**Comment by techsproutss** [comment]
Yes it worked thank you for support.
