### ISSUE TITLE
login  error

### ISSUE THREAD

**Issue by Hiddenleaf07** [marketcalls/openalgo#84]
![Screenshot_20241126_133612](https://github.com/user-attachments/assets/44441e24-09c3-4324-bb30-e32b1533a10c)

**Comment by marketcalls** [comment]
You are getting a 429 error. mean if suddently within a minute more than 5 login attempts one will get this error. Flask Limiter blocks the further request to avoid unwanted failed or repeated login requests.

**Comment by marketcalls** [comment]
This issue got fixed in the new release of v1.0.0.14 onwards.
Kindly test it out.
